apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-api-tester.fullname" . }}-postgresql
  labels:
    {{- include "my-api-tester.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret.data.properties.postgresql | nindent 2 }}
