name: basic build

on:
  workflow_call:
    outputs:
      artifact-key:
        description: 'build file artifact key'
        value: ${{ jobs.build.outputs.artifact-key }}
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/basic-build.yaml

env:
  artifact-key: ${{ github.repository }}-${{ github.sha }}-build-output

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-key: ${{ env.artifact-key }}
    steps:
      - name: check out source repo
        uses: actions/checkout@v4
        with:
          repository: k8s-1pro/kubernetes-anotherclass-api-tester
          ref: main

      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.6.1

      - name: Fix gradlew permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: upload jar
        uses: actions/upload-artifact@v3
        if: github.event_name == 'workflow_call'
        with:
          name: ${{ env.artifact-key}}
          path: build/libs/app-0.0.1-SNAPSHOT.jar
          retention-days: 1
