name: basic build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/base_cicd.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out source repo
        uses: actions/checkout@v4
        with:
          repository: k8s-1pro/kubernetes-anotherclass-api-tester
          ref: main

      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.6.1

      - name: Fix gradlew permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
