name: docker-image-build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker-image-build.yaml
      - .github/workflows/basic-build.yaml

env:
  checkout-path: 2121/build/docker

jobs:
  build-jar:
    uses: ./.github/workflows/basic-build.yaml
    secrets: inherit

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-jar
    steps:
      # 도커 세팅
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      ## 레포 체크 아웃 및 빌드 파일 다운로드
      - name: check out source repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.checkout-path }}

      - name: get artifact file
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build-jar.outputs.artifact-key }}
          path: 2121/build/libs

      ## 도커 빌드 및 업로드
      - name: docker build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.checkout-path }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ vars.REPOSITORY }}:v1.0.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
