name: k8s deploy

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/docker-image-build.yaml
      - .github/workflows/k8s-deploy.yaml

env:
  checkout-path: 2121/deploy/k8s

jobs:
  docker-build-and-push:
    uses: ./.github/workflows/docker-image-build.yaml
    secrets: inherit

  k8s-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubectl-version: ['v1.27.10']
    needs: [docker-build-and-push]
    steps:
      - name: checkout repository

        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.checkout-path }}
      - name: setup kubectle
        uses: azure/setup-kubectl@v3
        with:
          version: ${{matrix.kubectl-version}}

      - name: setup kubeconfig
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        with:
          cluster: ${{ secrets.OCI_OKE_CLUSTER_ID }}

      - name: deploy to k8s
        working-directory: ${{env.checkout-path}}
        run: |
          kubectl get po -A
          kubectl apply -f ./namespace.yaml
          kubectl apply -f ./pv.yaml
          kubectl apply -f ./pvc.yaml
          kubectl apply -f ./configmap.yaml
          kubectl apply -f ./secret.yaml
          kubectl apply -f ./service.yaml
          kubectl apply -f ./hpa.yaml
          kubectl apply -f ./deployment.yaml
